### ISSUE TITLE
recipe content

### ISSUE THREAD

**Issue by kasiawojczulanis** [nitwit2gitwit/recipes-2024#1]
to fill the content with proper recipe (otherwise you will have to make a dish out of your recipe;)

**Comment by reinhrst** [comment]
Maybe best to add a link to what you mean; @sslomkowski may only get to fixing this in 2 years and then have no idea what you're talking about :)

https://n2g-recipes-2024.claude-apps.com/recipes/lorem_ipsum.html

**Comment by kasiawojczulanis** [comment]
I can see reinhrst point and I appreciate the sslomkowski recipe. So to add a link I will create another issue, and this is rather solved, so I close it
