### ISSUE TITLE
Make your recipe more nerdy

### ISSUE THREAD

**Issue by reinhrst** [nitwit2gitwit/recipes-2024#10]
https://github.com/nitwit2gitwit/recipes-2024/blob/ee05174490d6135642d8ca372c78796f85fe4e71/recipes/corn-squared-beef.qmd#L2

Change this to `title: "Corn$^2$ Beef"` and see what happens :)

**Comment by kasiawojczulanis** [comment]
I tried it but did not commit as want the main author to experience the beauty of the code ;)

**Comment by reinhrst** [comment]
Using `$...$` you can make all kinds of math:

`$\int_0^1\frac{x^4(1-x)^4}{1+x^2}\,dx =\frac{22}{7}-\pi$`=$\int_0^1\frac{x^4(1-x)^4}{1+x^2}\,dx =\frac{22}{7}-\pi$

Just in case you ever need stuff like this on your website / in your paper

**Comment by LittleAuk47** [comment]
Thank you Kasia, I was sick on Thursday and Friday and this discovery has renewed my love for life.

And thank you for the tip Claude! Nothing but Dollar signs (if you know what I mean) ;)
