### ISSUE TITLE
Image missing from Pistacio Oats recipe

### ISSUE THREAD

**Issue by reinhrst** [nitwit2gitwit/recipes-2024#12]
Hey @PaulineBodson I'm afraid the image is missing from [your recipe](https://n2g-recipes-2024.claude-apps.com/recipes/good-day.html). Possibly you forgot to add the image while when you were committing.

Please fix, I would love to see what it looks like!

<img width="625" alt="image" src="https://github.com/user-attachments/assets/03f0f554-1322-46ea-8ceb-d97a488f62d4">

**Comment by PaulineBodson** [comment]
Hey @reinhrst, I guess I would need some help on that one.
Here are the steps I did, I have a picture on my desktop that I stored in: recipes-2024 > recipes > images 
Then when I am on my quarto website page: PistachioOat.qmd, I used the Insert button > Figure/Image ... and upload the picture that way. 

I try again to upload the image, but as you are saying, once I am opening the webpage it does not appear. 
I have warning message in Rstudio but the image still appears over there. Here are some screenshot of the error message and what I have on my computer. Maybe you will be able to help me out?

<img width="1413" alt="Screenshot 2024-11-29 at 09 22 38" src="https://github.com/user-attachments/assets/4a4d89c1-0752-452b-b0f9-12c87feda0aa">
<img width="1416" alt="Screenshot 2024-11-29 at 09 14 09" src="https://github.com/user-attachments/assets/39f4f84f-7ae7-4b83-bf07-77a1f4fac58d">

Everything works in my terminal, I don't get any error message

**Comment by reinhrst** [comment]
What happens if you do "git status" in terminal? I expect it will say there is an image untracked. Untracked means that it's not part of git (as in: git does not track what happens to it).

In that case, you do `git add recipe/images/imagename.jpeg` or so and then you can commit it.

Remember that commit only commits things that were added to the index before. So if you did not add the image, it will not get committed.

**Comment by PaulineBodson** [comment]
It is solved, thanks for your help!
