### ISSUE TITLE
Are you trying to piss off both Europeans and Americans at the same time?

### ISSUE THREAD

**Issue by reinhrst** [nitwit2gitwit/recipes-2024#15]
@kurkachatka Looking at <https://n2g-recipes-2024.claude-apps.com/recipes/carrot-cake.html> I wonder if you're trying to piss off the whole world? Half the ingredients are in normal imperial units (named that way because they were introduced by Emperor Napoleon), but Americans refuse to acknowledge their superiority, the other half are in standard units (named this way because you need standardised cups and tea spoons or you're fucked), and no European understands this.

If indeed the aim is to annoy anyone, can I suggest you rewrite it all in the proper [Furlong-Firkin-Fornight system](https://en.wikipedia.org/wiki/FFF_system)?

**Comment by kasiawojczulanis** [comment]
Amazing how many things we can learn from each other, apart from git enviroment ;) 
[FFF system - I love it!]

**Comment by kurkachatka** [comment]
Oh no, I used the wrong keywords for the commit message and I didn't get the cool closing of this issue. I will now do another pointless commit, to fix the commit msg of the previous fix...
