### ISSUE TITLE
Untracked file .DS_Store

### ISSUE THREAD

**Issue by PaulineBodson** [nitwit2gitwit/recipes-2024#17]
I was able to commit my image PistachioOat and push it to the common repository but I still have a weird file that is mentioned as not tracked (see screenshot). 

<img width="658" alt="Screenshot 2024-11-29 at 12 17 44" src="https://github.com/user-attachments/assets/75428ced-46d5-45d2-9f95-9e2d587231cf">

Do you know what that could be? As it does not have the picture format, it does not appears in the images file

**Comment by reinhrst** [comment]
.DS_Store is a small file that MacOS annoyingly puts everywhere. I think that it contains thumbnails of the files in the directory. That is why the first time you open a directory it takes a long time to generate all thumbnails, and the next times they are there a lot quicker.

These files should not be checked in. I think it's completely OK to add a line to `.gitignore` that reads `.DS_Store`.

The best solution would be to add the `.DS_Store` line to a global gitignore file. This has two advantages:
1. It will apply to all current and future repositories, meaning you don't have to add the file again every time.
2. You don't bother everyone else with the fact that you work on Mac. This is not such a big deal on a small project, but if you have a project with 1000 contributors, and everybody starts to add files for their specific system to `gitignore` it will become unmanageable.

My rule is (but again, for this repo I think adding it to the `.gitignore` in the repo is completely fine):
- If a file is generated by the code that runs in the repo (e.g. quarto generates a `_site` directory), then it should be in the `.gitignore` of this repo
- If it's something that your editor or operating system generates -> global gitignore (which technically means that also `.Rproj.user`, `.Rhistory`, `*.Rproj`, the last three lines of the current gitignore, should be in global gitignores....)

How to add it to a global gitignore, follow these steps:
- `nano .gitignore_global` and then add the file
- `git config --global core.excludesfile ~/.gitignore_global`

Afterwards the .DS_Store files _should_ not show up anymore in git status.

Let me know if this solves it.

**Comment by PaulineBodson** [comment]
Hi Claude, I followed the step you are describing by doing the following: 
1. I went to my desired directory: `cd recipes`
2. I wanted to see the file: `git status`
3. I went into nano with the following command: `nano .gitignore_global`
4. When I was in nano I entered the name of my file (see screenshot): I first press `CTRL + O` to save the file then press `Enter` then `CTRL + X`

![Screenshot 2024-12-02 at 08 49 51](https://github.com/user-attachments/assets/2db53483-8940-453f-8c36-f1c4b7d48318)


6. Finally, I ran the command you suggested: `git config --global core.excludesfile ~/.gitignore_global`
But when I type `git status` (see second screenshot), I have `.gitignore_global` which added itself to untracked files
![Screenshot 2024-12-02 at 08 59 20](https://github.com/user-attachments/assets/76b4ba9f-fb36-4223-870f-84cd32db344e)

Could you help me out on that one, please

**Comment by reinhrst** [comment]
My bad, I skipped a step in the instructions :).

`git config --global core.excludesfile ~/.gitignore_global` means that the global git-ignore file is in `~` which is your home directory. And now you made the file in your repository directory.

You should be able to fic this by doing `mv .gitignore_global ~` (meaning move gitignore-global to the home directory)

**Comment by PaulineBodson** [comment]
It's fixed, thanks for your help
