### ISSUE TITLE
fix email address in your local git

### ISSUE THREAD

**Issue by Mauoke** [nitwit2gitwit/recipes-2024#18]
@PaulineBodson's commits are always doubled; it's written that she authored and committed. What does that mean? Why is she the only one with this?

**Comment by reinhrst** [comment]
Good find :)

As you may remember, back when you made the first commit, git asked you for your name and your email address. This information is stored in each commit you make.

When you push something to GitHub, there is the email address in the commit, and the email address that you used to register to GitHub. If these two are the same, the message on the timeline is something like "Claude committed yesterday".

If the two differ then the message will be something like "X authored and Y committed"; remember that `git` is in the basis a distributed version control system, so it's very much possible that Claude pushes his work to Maureen, and Maureen pushes everything to GitHub; in that case it's nice that GitHub shows that these are two different people (in case you want to go there and complain). I have to say that I think that in "X authored and Y committed" the idea is that X wrote the code (and, confusingly, committed to git) and Y pushed it to GitHub, but it might be different.

If you check Pauline's commit in your own terminal (e.g. `git show 81fe6`) you will see that her email address is wrong in there. So I guess this ticket can be changed into one for @PaulineBodson to [fix her email address in her local git](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address).

**Comment by PaulineBodson** [comment]
Done, I've changed my email
