### ISSUE TITLE
Dutch and German word needed

### ISSUE THREAD

**Issue by kasiawojczulanis** [nitwit2gitwit/recipes-2024#21]
https://github.com/nitwit2gitwit/recipes-2024/blob/892802a2317210882282e3f0cf15a07f2f704a29/recipes/good-day.qmd#L15

Following kurkachatka request, to make the text more accesible, I would like to translate the French expression I used to other languages. I could handle that with couple of languages but with German and Dutch I would prefer to ask for the help the experts :) 
**Claude,** "C'est la vie/That's the life" - how that would be in Dutch*?
**Kristin,** "C'est la vie/That's the life" - how that would be in German*?
**Others** - any other language you could add here?

**Comment by reinhrst** [comment]
"Zo is het leven nou eenmaal"

**Comment by Mauoke** [comment]
I can help you with a bit of italian "è la vita"

**Comment by kristinpiening** [comment]
Nice idea! :)
"So ist das Leben"

**Comment by sslomkowski** [comment]
"Sånn er livet" på norsk!
