### ISSUE TITLE
Add 🥕🥕🥕

### ISSUE THREAD

**Issue by reinhrst** [nitwit2gitwit/recipes-2024#23]
https://github.com/nitwit2gitwit/recipes-2024/blob/1b8f479007216953520258c45068424d33fb8e63/recipes/carrot-cake.qmd#L30

See [here](https://www.rbolt.me/blog/technical-blog/posts/20210823-original-emojis/) how to add emojis.

(or just find a carrot emoji online and copy-paste it into the text)

**Comment by kasiawojczulanis** [comment]
Insprirating, and works with copying the stuff but the link does not work 🙂

**Comment by reinhrst** [comment]
@kasiawojczulanis 
Not sure what does not work for you with the link.

In order for the :carrot: to work (it works in GitHub, but on quarto) you need to add the special header. See 833aaa (or in the linked branch on the right). At least this works on my computer :)

**Comment by kurkachatka** [comment]
@reinhrst 
Unfortunately, same as before I get '????' in quarto after rendering :carrot:
You can see the difference between the branch [emojis](https://github.com/nitwit2gitwit/recipes-2024/blob/4e5fa072217fd3fcc78f5fd44a519136ca4c17aa/recipes/carrot-cake.qmd#L30) that I have made:
https://github.com/nitwit2gitwit/recipes-2024/blob/4e5fa072217fd3fcc78f5fd44a519136ca4c17aa/recipes/carrot-cake.qmd#L30
and branch [23-add carrots](https://github.com/nitwit2gitwit/recipes-2024/blob/833aaa9d6b1117b7719740da54704c0edab4e855/recipes/carrot-cake.qmd#L31) that you've made:
https://github.com/nitwit2gitwit/recipes-2024/blob/833aaa9d6b1117b7719740da54704c0edab4e855/recipes/carrot-cake.qmd#L31

I rebased emojis into main branch, and the carrot does not render on the webpage as well. In my RStudio it looks fine, but after pushing it changes from carrot to question marks.

RStudio:
![image](https://github.com/user-attachments/assets/f9daadac-2332-4fa7-84d0-a650ac2a13a0)

Webpage:
![image](https://github.com/user-attachments/assets/cc5ea6b1-b64a-4037-831f-7287c50bcff1)

**Comment by kurkachatka** [comment]
This is exactly what I am doing, but after I type ':carrot:'  as soon I do it changes into 🥕 both in Source and Visual. And later it renders to ????

**Comment by reinhrst** [comment]
Try to type this in the source editor. I expect it will only change in the visual editor.

Worst case, use nano 😊

**Comment by kristinpiening** [comment]
Hey Marta,
I just tried adding a brain emoji using the visual editor in R. I do not know which way you tried but this way it worked for me (at least this time :)). Open the ‘Visual’ editor in R Studio, select the Insert tab ‘Special Characters’ ‘Insert Emoji …’ and then selecting you desired emoji from a large list. Fingers crossed it will work for you when you add the carrot!

Also, I like your colorful header! This is super cool! How can I find out about the colors I can use?

**Comment by reinhrst** [comment]
@kristinpiening make a separate issue for the second question please.

@kurkachatka you can open the file in nano by just in the terminal type nano recipes/carrot-cake.qmd. Whatever magic Rstudio is doing (magic carrots...), nano will not do it. Not sure what will happen next time you open the file in rstudio though.

**Comment by reinhrst** [comment]
@kurkachatka I tried, and for me when I try to type `:carrot:` in the visual tab, it indeed replaces it by the carrot emoji (which is _not_ what we want). In that case, also on the Source tab it's an emoji now.
<img width="245" alt="image" src="https://github.com/user-attachments/assets/9c067e7c-242a-4ca6-bcea-3b1c1be21918">

However if I _type_ into the source tab, it does not do this magic and just puts the string `:carrot:` in there.
<img width="292" alt="image" src="https://github.com/user-attachments/assets/e6f1bded-cfbb-469c-a24c-5ee6d12b1d4f">

Even if I then switch to the visual tab, it still does not magic-replace it for the emoji:

<img width="383" alt="image" src="https://github.com/user-attachments/assets/a3ce4164-bb59-449c-a829-358288e2ef88">


Editing in nano will work for sure, but just wanted to show that I think it can also be done directly in R studio.

**Comment by kurkachatka** [comment]
I pulled your changes to my recipes and in both source and visual your brain is :brain:

![image](https://github.com/user-attachments/assets/6a776f12-5905-4481-bf97-24b3553c8cb8)

I added a line containing ':carrot:' in the source just as you, committed and pushed it. It still doesn't work after rendering, although your 🧠  is still there....
![image](https://github.com/user-attachments/assets/4cccc33b-e354-452a-83f3-7c0f11752e28)

As for nano:

1) I figured it could be any text editor, so I tried it in Notepad, see 746f398
2) I also did it in nano (db9faba) and it didn't work as well:
![image](https://github.com/user-attachments/assets/30e0656d-f41f-4cdf-b5b6-21882be1a77c)

Maybe I'm a muggle....

**Comment by reinhrst** [comment]
Ahhh, I think I see where the problem is.

A certain character (and emojis are characters, as far as the computer is concerned) that is displayed on the webpage, can be represented in the source in different ways.

Say that we want to show the character X, we have basically three ways:
1. type a literal `X` in your quarto document
2. type some command that tells quarto to put an X in the HTML that it generates
3. type some command that tells a browser to put an X

Even though not always all three ways are available, you will need one of these three ways. The same so with Emojis.

Option 1 is what Kristin did with 🧠 . You can see this because the 🧠 is shown when opening the source (in nano, or in the source tab). Option 1 is also what happens if you use Insert -> Emoji in RStudio, or is produced through RStudio magic when typing `:brain:` in the visual tab.

Option 2 is what we're trying to do when we type `:brain:` _into the source tab_ or into nano .
The idea is that it's not getting replaced in the source, but should become a 🧠 in the rendered page.
This only works if we tell quarto that we want to use an extension that supports this; this is what we do by adding the following to the YAML at the top: `from: markdown+emoji`.
If this is omitted, it will just render as `:brain:`.

Option 3 is also possible just type `&#x1F9E0;` into the source.
However, annoyingly, as soon as you switch to "visual" tab, the icon is shown but gets replaced into option 1.
So this will only work if you stay in source mode forever, or if you use nano.

Now, why option 1 does not work for you @kurkachatka, this has to do with character encoding.
Even though since many years there is a standard on how strange characters (anything except letters without accents, digits, and punctuation) should be represented, some systems still use older (incompatible) methods.
It seems to me that your RStudio uses such an older method.
Probably something that can easily be fixed, but then we wouldn't be having so much fun with this ticket :).
(btw this was also why your µ in µl did not show correctly for some people).

So the best way to fix this I think, is to try option 2 :)
