### ISSUE TITLE
Adding a photo

### ISSUE THREAD

**Issue by LittleAuk47** [nitwit2gitwit/recipes-2024#24]
I cannot seem to add a photo to my recipe. I use the insert tab in RStudio to put a photo, but it does not show up in the end. The recipe just displays a little icon instead (see the corn sqaured beef recipe). How do I fix this

**Comment by kurkachatka** [comment]
You need to commit the image to the repository together with your quarto recipe file. The directory storing images is recipes-2024/recipes/images

Check out issue #12  I believe a similar issue was resolved there

**Comment by LittleAuk47** [comment]
Ahh thank you so much bestie
