### ISSUE TITLE
Should I be worried about Warnings and 404: Not Found

### ISSUE THREAD

**Issue by PaulineBodson** [nitwit2gitwit/recipes-2024#26]
Hi, when I am saving and rendering my .qmd file, everything works but I get a recap with a lot of warning messages and an error 404. I was wondering if other people had the same thing in their Rstudio terminal and if I should do something about it? 

<img width="871" alt="Screenshot 2024-12-02 at 09 16 52" src="https://github.com/user-attachments/assets/dc699dd4-c6bb-40d7-b670-64e25f374bab">

**Comment by kurkachatka** [comment]
I get some of the same warnings, but not as many as you do.

![image](https://github.com/user-attachments/assets/b3911908-8114-4ecd-bea8-0d62978584ae)

**Comment by AntoineGrissot** [comment]
I've had the same issue, I wanted to ask about it last week but didn't get the chance,
Usually saving the .qmd then closing it and reopening it would fix the problem for me, good 'ol IT fix : "have you tried turning it off and on again"

**Comment by PaulineBodson** [comment]
Hey @AntoineGrissot, my code is working fine, I was just curious to see if you were also going through it. Thanks, for your feedback
