### ISSUE TITLE
Changes happening in main and other branch at the same time

### ISSUE THREAD

**Issue by kurkachatka** [nitwit2gitwit/recipes-2024#30]
I'm doing playtime 7 (yes, a couple of hours before the lesson), and something weird is happening, as far as my understanding of git goes (so not too far). I'm trying to get a conflict and so:

1)  I have a shopping.md on my master branch
2) I create a new branch 'crash'
3) I edit the shopping.md there (number of bottles of milk)
4) I switch back to master, and I would expect the shopping.md to be unchanged here. Howeve,r it has the exact change I made on branch 'crash'

![image](https://github.com/user-attachments/assets/65a24e3b-6718-4720-ae15-463a1753340d)

Therefore I can't get the conflict, because master follows changes I made on other branches. But that's not how branches work, right?

**Comment by kurkachatka** [comment]
Was it because shopping.md was not staged for commit on master? I committed it on master, then I made a change in crash and now it works. Meaning the changes don't repeat between branches and I get the conflict.
I'm confused 😵

**Comment by reinhrst** [comment]
Discussed in class
