### ISSUE TITLE
Missing picture

### ISSUE THREAD

**Issue by AntoineGrissot** [nitwit2gitwit/recipes-2024#7]
https://github.com/nitwit2gitwit/recipes-2024/blob/eeb5560c3578798ffc8cac9562067f39cc6f661a/recipes/dauphinois.qmd#L8

![image](https://github.com/user-attachments/assets/06ed24b4-4ce7-43a3-bef4-e9a18311e84f)

**Comment by kristinpiening** [comment]
No picture for this delicious recipe? I guess we will need to spend one afternoon / evening after work to try it out, take a picture, and upload it to the website :)
