### ISSUE TITLE
Link missing

### ISSUE THREAD

**Issue by AntoineGrissot** [nitwit2gitwit/recipes-2024#8]
https://github.com/nitwit2gitwit/recipes-2024/blob/26c3f6d4191ddc3905eca884c83de99cba3718d0/recipes/Hefezopf.qmd#L9

![image](https://github.com/user-attachments/assets/a2f23419-0617-4ed2-b4d9-7e4a8cd813d4)

This looks like a very promising website, but I am too lazy to copy-paste it. Can you please add a link ?

**Comment by kristinpiening** [comment]
Good question if I can do that - need to check how other people did it so you can enjoy this wonderful website easily without copy-paste :)
