### ISSUE TITLE
Clarify American culture

### ISSUE THREAD

**Issue by reinhrst** [nitwit2gitwit/recipes-2024#9]
I'm very confused by [your recipe](https://n2g-recipes-2024.claude-apps.com/recipes/corn-squared-beef.html).

Does corned beef already have corn in it? If so, what does that mean for the optimum ratio (is it 1 can corned beef and 1 can corn, or still 2 cans of corn, effectively making cubed corn beef (I guess extra points if you manage to shape it in a cube....).

Feel free to use this image that chatGPT kindly created

![image](https://github.com/user-attachments/assets/1b3be7c9-07cd-4d31-85b1-fc7f7ca47bac)

**Comment by reinhrst** [comment]
I should tag @LittleAuk47 to this :)

**Comment by Mauoke** [comment]
(I was trying to see if I could assigned people even if it was not my issue, don't mind me)

**Comment by kristinpiening** [comment]
Omg, chatGPT created a very interesting image! :))

**Comment by LittleAuk47** [comment]
Note made in recipe showing that there is no corn in corned beef.
